"""add_folder_metadata

Revision ID: 3892c70922b8
Revises: a248358fd4cd
Create Date: 2026-07-13 12:25:19.153399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3892c70922b8'
down_revision: Union[str, Sequence[str], None] = 'a248358fd4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('folder_size', sa.BigInteger(), nullable=False))
    op.add_column('folders', sa.Column('file_count', sa.Integer(), nullable=False))
    op.add_column('folders', sa.Column('children_count', sa.Integer(), nullable=False))
    op.add_column('folders', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('folders', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('folders', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('folders', sa.Column('updated_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'folders', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'folders', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'updated_by')
    op.drop_column('folders', 'created_by')
    op.drop_column('folders', 'version')
    op.drop_column('folders', 'last_activity_at')
    op.drop_column('folders', 'children_count')
    op.drop_column('folders', 'file_count')
    op.drop_column('folders', 'folder_size')
    # ### end Alembic commands ###
